# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6c3fd6f586b9480a2a7eaae12206f664ab996ba3a1a89efb4e00949588c5779e10e43d13506c7a19bf00ed5361f2937f7a0f0fb3dbe342fbbd8909288eb6fa

test:
  secret_key_base: 9cfdfa7efb5badc5fb61b989cf5ca9c7cbb4daea995929b7506c2b9c65414294e7fa0ce5e6979261ef7ecded20063247ffa3b2f61ed0433b3a2f0ff3d14b4df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
